---
  - hosts: all
    remote_user: root
  
    tasks:
    - name: Checking ping command
      shell: ping -n 10 ashnik.com
  
    - name: installinh the latest version of Nginx web server
      yum:
        name: nginx
        state: latest
      become: yes
  
    - name: Deploying  sample html file to Nginx & Copying files to www
      copy: src=config/index.html dest=/usr/share/nginx/html/ mode=0644
      become: yes
  
    - name: Deploy changes to nginx.conf
      copy: src=config/nginx.conf dest=/etc/nginx/ mode=0644
      become: yes
  
    - name: Making sure the Nginx service is running
      service:
        name: nginx
        state: started
      become: yes
  